### ISSUE TITLE
Unavailable on docker hub

### ISSUE THREAD

**Issue by bebehei** [czka/archlinux-docker#2]
Do you mind pushing it to docker hub and updating it regularly?

**Comment by czka** [comment]
Good idea, but I don't want to be doing this manually. A (Travis-based, probably) CI pipe and automated detection of new bootstrap tarballs being published would be in order. This will take a bit of thinking and doing, and I'm short of time right now.

I'll keep this ticket open to remind me about it. Or, if you have some recommendation yourself how to go about this please share it.

Besides, there is still the the "official" Arch Linux docker image [1], last updated 1.5 year ago, which we should replace rather than create a new one. If you can arrange that with the maintainer it would help.

[1] https://hub.docker.com/r/base/archlinux/

**Comment by bebehei** [comment]
Yes, I know the "problems". You may have seen my bugreport in his repo: tmc/dockerfiles#11

Actually, I want to start working on some arch-specific stuff. But there is **no** container, which is available on docker hub **and** reasonably up to date.

I thought you may have had already an idea, how to fix this.

**Comment by The-Compiler** [comment]
This sounds like a good idea! Since some while, Travis can run [cron jobs](https://docs.travis-ci.com/user/cron-jobs/), i.e. periodically run a build without any new pushes.

Then the Travis CI file only needs to do those things:

- Find the newest upstream Arch tarball and download it (probably the most "complicated" step)
- Run `tar_fix.py`
- Build and upload to Docker Hub, similarly to what I do [in this travis.yml](https://github.com/qutebrowser/docker-travis/blob/master/.travis.yml)

I'd be happy to help with these things so my [Archlinux builds](https://travis-ci.org/qutebrowser/docker-travis/jobs/194936985) there hopefully get a bit less cumbersome (based on `base/archlinux` currently) - however, this will be in about 2 weeks as I'm busy with exams currently.

However, other than writing a script for the first step and helping with the `.travis.yml`, I'm not sure what else I can do - for the rest, probably only @czka can set things up :wink:

**Comment by terencewestphal** [comment]
@The-Compiler 

> - Find the newest upstream Arch tarball and download it (probably the most "complicated" step)

https://github.com/terencewestphal/get-archlinux-bootstrap

Here you go my friend. I was thinking the same thing.

**Comment by czka** [comment]
Guys,

Thanks for being supportive. I'm in the midst of some important changes in my life, and things will stay so for the next several weeks. I'm just to busy to give this stuff a good look. Please keep your ideas and solutions coming though. We'll get back to this once the dust settles. Cheers!

**Comment by bebehei** [comment]
@czka Ok, I got it ;-)

@The-Compiler your reference to travis cronjobs is golden. Love it.

So I've got everything up:
Repo: [bebehei/archlinux-docker](https://github.com/bebehei/archlinux-docker)
Travis: [bebehei/archlinux-docker](https://travis-ci.org/bebehei/archlinux-docker)
Images: [archimg/base](https://hub.docker.com/u/archimg/)

Ironically travis-ci.org weblogin is currently down and I cannot login to configure cronjobs. So this has to wait another day. After this is fixed by travis, it'll just be some clicks to get daily updated images.

I hope travis webinterface is fixed tomorrow.

**Comment by The-Compiler** [comment]
Pushed my own one here now: https://github.com/The-Compiler/archlinux-docker/blob/master/.travis.yml

I intend to do some more images with bigger stuff baked in I use in various configurations, which is why I went for my own build :wink:

**Comment by bebehei** [comment]
@The-Compiler I'd really like to do things together here. Shall I invite you into @archimg's organisation?

**Comment by The-Compiler** [comment]
@bebehei I appreciate that, but since I'm already going to need the infrastructure to build more customized images (e.g. ones with Qt installed), doing it this way just seemed easier to me. I already have a lot on my plate with the projects I'm involved in, so I probably won't be able to contribute much I'm afraid.

**Comment by dumblob** [comment]
@bebehei thank you for the repo. For how long do you plan to maintain the repository? I'm asking due to reliability issues. Once answered, you can add this information to the README in the repo itself.

By the way I could contribute to the repo as I'm interested in a minimal arch image, but unfortunately I can assign at most about 2 hours per month for this. I'm curious what @czka will do after his "transition" time is over.

**Comment by bebehei** [comment]
> @bebehei thank you for the repo. For how long do you plan to maintain the repository? I'm asking due to reliability issues. Once answered, you can add this information to the README in the repo itself.

It gets built by a travis-ci daily cronjob. So you don't have to worry, that your packages are too old. If I would ever stop using those images, maintenance is just as easy as accepting new PRs.

**Comment by bebehei** [comment]
I would close this issue. The archlinux-image with highest reputation (`base/archlinux`) gets now also updated by @archimg. So I don't see any need here to have another basic archlinux image.
