### ISSUE TITLE
Official Archlinux docker images

### ISSUE THREAD

**Issue by The-Compiler** [czka/archlinux-docker#8]
According to [Arch Weekly 2](http://vdwaa.nl/arch/weekly/news/arch-weekly-2/), there's now an [official Archlinux Docker image](https://hub.docker.com/r/archlinux/base/) available ([source](https://github.com/pierres/archlinux-docker)) - I guess that makes this obsolete in some way, no?

**Comment by czka** [comment]
In some. It's different enough though not to call it obsolete though IMO. Eg. you can run it on any GNU/Linux, while [the other one you refer to](https://github.com/pierres/archlinux-docker) will run on Arch only and it requires root access, which can be avoided with my setup. And since I have added haveged into the mix, my setup is VM-friendly. Plus I use rankmirrors ;). Finally, it seems that (haven't checked that in detail though) both setups end up with slightly different set of packages. I'd say mine is closer to whatever the Arch devs mean as a "minimal valid install", reflected in their bootstrap tarballs content, but that's just my unsuported claim; and I should consider dropping a couple packages, like systemd

All in all, I think it will stay. People still clone and star it, which means somebody finds it useful.
